# ------------------------------------------------------------------------------
#  Copyright Christopher Kormanyos 2023.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)
# ------------------------------------------------------------------------------

name: serial_win32api
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  msvc-release-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.2
      - name: msvc-release-x64
        shell: cmd
        working-directory: ./
        run: |
          MSBuild -m serial.sln -p:useenv=false -p:Configuration=Release -p:Platform=x64 /t:Rebuild
          dir %cd%\x64\Release\serial.exe
